### ISSUE TITLE
Looty for Garena PoE

### ISSUE THREAD

**Issue by dualwind** [benjaminjackman/looty#3]
Hi, may i know how to configure looty to read from garena path of exile?

**Comment by benjaminjackman** [comment]
I am not sure because I haven't used Garena before, you can try to build the project and change the urls. Let me know if you are interested in doing that.

**Comment by benjaminjackman** [comment]
If you want to test it out let me know, I can give it a shot, no promises it will work however.

**Comment by semasping** [comment]
Hi. I want try to test. Garena rus using url: http://web.poe.garena.ru/
where i must change this urls? 
in looty-master\looty\src\main\scala\looty\poeapi ? or somewhere?

Thank you for you work. It`s awesome.

**Comment by benjaminjackman** [comment]
I should make some build instructions, they aren't that difficult. Have you built a Scala project with SBT before?

**Comment by semasping** [comment]
no i haven`t. 
and i have Windows as main OS, but i can install need OS on virtual machine in VirtualBox.

**Comment by benjaminjackman** [comment]
It should work in windows, the only thing that changes is how you would
install SBT (simple build tool) you will need to

1. Have java installed.

2. Then you will need to install SBT:
http://www.scala-sbt.org/0.12.4/docs/Getting-Started/Setup.html

3. After that you can clone the Looty repo, (for example into
C:/githubs/looty)

4. go into it's directory (cmd; cd C:/githubs/looty) and run

sbt

at a command prompt (make sure sbt and java is in your path)

5. sbt will then start an interactive terminal you should be able to type

fastOptJS

to build the source code.

6. Once it is build, go to

chrome://extensions

in google chrome and

7. check developer mode

8. press Load unpacked extension...

9. then navigate to the root looty folder
beware there is another looty folder under the root looty folder you
checked out from github we will want to go into that folder:

So the path will be something like:

C:/githubs/looty/looty/target/web/public/main

if  C:/githubs/looty is where you cloned github too

This is where fastOptJS will output all the files needed for the extension.

10. This will load the extension, the urls are a bit different in
development mode
so go to a page in it which will have a url like:

chrome-extension://lgaojheahkjklbkkffhdhfmpejaiemeb/looty.html#/standard-grid

and change looty.html

to looty-dev.html

so it would become this:
chrome-extension://lgaojheahkjklbkkffhdhfmpejaiemeb/looty-dev.html#/standard-grid

at this point looty should be working from a PathOfExile account and
downloading your items for standard.

If you get this far let me know! No worries if not, I understand how
complicated this unfortunately. Maybe the easiest way would be for me just
to create a garena account and give it a shot. Thanks for volunteering to
at least give it a shot, a lot of users have asked for garena support. If
you get this to work, I will fold the changes back into looty proper and
add a garena mode option into the settings.

**Comment by semasping** [comment]
in step 4 
--------------------------------------------------------------------------
  [info] Resolving com.typesafe#jse_2.10;1.0.0 ...
  [info] Resolving com.typesafe#jse_2.10;1.0.0 ...
[warn]  module not found: com.typesafe#jse_2.10;1.0.0
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe/jse_2.10/1.0.0/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe/jse_2.10/1.0.0/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\semas\.ivy2\local\com.typesafe\jse_2.10\1.0.0\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/jse_2.10/1.0.0/jse_2.10-1.0.0.pom
[info] Resolving com.typesafe#npm_2.10;1.0.0 ...
  [info] Resolving com.typesafe#npm_2.10;1.0.0 ...
[warn]  module not found: com.typesafe#npm_2.10;1.0.0
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe/npm_2.10/1.0.0/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe/npm_2.10/1.0.0/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\semas\.ivy2\local\com.typesafe\npm_2.10\1.0.0\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/npm_2.10/1.0.0/npm_2.10-1.0.0.pom
---------------------------------------------------------------------------
and fail of launch "sbt"

full log http://pastebin.com/yBs0JQad

**Comment by benjaminjackman** [comment]
Ok that is a bug in the build file (I think). I will need to fix it ASAP,
also it reminds me that you might need to have nodejs installed as well.

**Comment by benjaminjackman** [comment]
also I am not sure what to do about the jline errors, I am not sure if they
are fatal or not. It might not be a deal breaker.

**Comment by benjaminjackman** [comment]
ok pushed a fix to master for the dependency not found issues, can you try
again, I will look into the jline ones now too

**Comment by benjaminjackman** [comment]
This is a more upto date page: http://www.scala-sbt.org/0.13.5/docs/Getting-Started/Setup.html

I sorry about that.

**Comment by benjaminjackman** [comment]
If you installed manually you will need to  download a more recent version of sbt-launch.jar and replace the other one you downloaded with it:
(http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.5/sbt-launch.jar)
then you might need to update the bat file too.

If you can get that to work, I think you are pretty close to having it build.

**Comment by semasping** [comment]
with 0.13.5 - step 4 - ok

**Comment by semasping** [comment]
step 5  = 

[info] downloading https://repo1.maven.org/maven2/jline/jline/2.12/jline-2.12.jar ...
[info]  [SUCCESSFUL ] jline#jline;2.12!jline.jar (695ms)
[info] Done updating.
[trace] Stack trace suppressed: run last looty/web-assets:managedSources for the full output.
[error] (looty/web-assets:managedSources) java.util.NoSuchElementException: None.get
[error] Total time: 146 s, completed 12.05.2015 19:18:00

**Comment by benjaminjackman** [comment]
Ok that is what happened when you typed ?
fastOptJS

if so can you try typing in 

last fastOptJS

after and pasting in the error message

and then try again and type in 

last looty/web-assets:managedSources

and again past the message?

**Comment by benjaminjackman** [comment]
Also I pushed up an updated version of master that should make it easy for you to change the url
it will be in the file

looty/looty/src/main/scala/looty/poeapi/PoeRpcs.scala

there is a variable called basePoeUrl near the top set to "http://www.pathofexile.com" you can try the garena version of that url.

**Comment by benjaminjackman** [comment]
also try running the command 

clean

in sbt

then run fastOptJS again (something might in there from the previous build when I told you to use the older version)

**Comment by semasping** [comment]
C:\poe\works\looty>git pull
remote: Counting objects: 11, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 11 (delta 7), reused 4 (delta 0), pack-reused 0
Unpacking objects: 100% (11/11), done.
From https://github.com/benjaminjackman/looty
   52abb7c..e9e3590  master     -> origin/master
Updating 52abb7c..e9e3590
Fast-forward
 looty/src/main/scala/looty/poeapi/PoeRpcs.scala | 14 ++++++++------
 looty/src/main/scala/looty/views/Alerter.scala  |  6 +++---
 2 files changed, 11 insertions(+), 9 deletions(-)

C:\poe\works\looty>sbt
Java HotSpot(TM) Client VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[info] Loading project definition from C:\poe\works\looty\project
[info] Set current project to root (in build file:/C:/poe/works/looty/)
> clean
[success] Total time: 0 s, completed 12.05.2015 19:54:14
> fastOptJS
[info] Updating {file:/C:/poe/works/looty/}looty...
[info] Resolving org.scala-lang#scala-library;2.11.4 ...
  [info] Resolving com.typesafe.play#twirl-api_2.11;1.0.4 ...
  [info] Resolving org.apache.commons#commons-lang3;3.1 ...
  [info] Resolving org.scala-lang.modules#scala-xml_2.11;1.0.1 ...
  [info] Resolving org.scala-lang.modules.scalajs#scalajs-library_2.11;0.5.6 ...
  [info] Resolving org.scala-lang.modules.scalajs#scalajs-dom_sjs0.5_2.11;0.6 ...
  [info] Resolving org.scala-lang.modules#scala-async_2.11;0.9.2 ...
  [info] Resolving biz.cgta#otest-sjs_sjs0.5_2.11;0.1.12 ...
  [info] Resolving org.scala-sbt#test-interface;1.0 ...
  [info] Resolving org.scala-lang#scala-reflect;2.11.1 ...
  [info] Resolving biz.cgta#oscala-sjs_sjs0.5_2.11;0.2.1 ...
  [info] Resolving biz.cgta#otest-sjs_sjs0.5_2.11;0.1.14 ...
  [info] Resolving biz.cgta#serland-sjs_sjs0.5_2.11;0.2.1 ...
  [info] Resolving biz.cgta#cenum-sjs_sjs0.5_2.11;0.2.1 ...
  [info] Resolving org.scala-lang.modules.scalajs#scalajs-jquery_sjs0.5_2.11;0.6 ...
  [info] Resolving org.webjars#jquery;1.10.2 ...
  [info] Resolving com.github.japgolly.scalajs-react#core_sjs0.5_2.11;0.4.1 ...
  [info] Resolving com.scalatags#scalatags_sjs0.5_2.11;0.4.0 ...
  [info] Resolving org.scala-lang.modules.scalajs#scalajs-compiler_2.11.4;0.5.6 ...
  [info] Resolving org.scala-lang#scala-compiler;2.11.4 ...
  [info] Resolving org.scala-lang#scala-reflect;2.11.4 ...
  [info] Resolving org.scala-lang.modules#scala-xml_2.11;1.0.2 ...
  [info] Resolving org.scala-lang.modules#scala-parser-combinators_2.11;1.0.2 ...
  [info] Resolving jline#jline;2.12 ...
[info] Done updating.
[trace] Stack trace suppressed: run last looty/web-assets:managedSources for the full output.
[error] (looty/web-assets:managedSources) java.util.NoSuchElementException: None.get
[error] Total time: 1 s, completed 12.05.2015 19:54:24
>

**Comment by benjaminjackman** [comment]
ok same bug then, can you type in

last fastOptJS

**Comment by semasping** [comment]
ок

**Comment by semasping** [comment]
> last fastOptJS
> last looty/web-assets:managedSources
java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:313)
        at scala.None$.get(Option.scala:311)
        at Build$$anonfun$1$$anonfun$apply$1.apply(Build.scala:69)
        at Build$$anonfun$1$$anonfun$apply$1.apply(Build.scala:64)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
        at Build$$anonfun$1.apply(Build.scala:64)
        at Build$$anonfun$1.apply(Build.scala:13)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[error] (looty/web-assets:managedSources) java.util.NoSuchElementException: None.get
>

**Comment by benjaminjackman** [comment]
I am wondering if it still might be an sbt version issue, I will see if I can find a link to an even newer version. In linux the sbt launcher will automatically update itself. I don't see it doing that here as best I can tell.

Can you try downloading this version of the sbt jar:

https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.6/sbt-launch.jar

**Comment by semasping** [comment]
in 10 minutes

**Comment by benjaminjackman** [comment]
if that doesn't work I will try to get it building on my windows machine tonight and update the build instructions, sorry for the difficulty so far. I develop in linux so I haven't actually ever built sbt in windows, sorry for the difficulty you have encountered so far.

**Comment by benjaminjackman** [comment]
before downloading (or after if you already have)

can you also try running it this way:

`sbt`

Then when inside of sbt

`project looty`

The type 

`fastOptJS`

**Comment by semasping** [comment]
sorry about windows user :) 
in all cases i get the same error.

I will try to setup ubuntu in virtual machine.

**Comment by benjaminjackman** [comment]
no need to apologize, I am just sorry I can't give better feedback, some of the same problems might occur in ubuntu so I am sort of grasping at straws. Let me try running my own instructions on a fresh aws machine.

**Comment by benjaminjackman** [comment]
#Building Looty on Ubuntu 14.04 Fresh AWS Machine (t2.medium w/ 30GB EBS HDD)
#I started a fresh AWS instance then there were the exact commands I managed to run to get it started

`sudo apt-get update`

`sudo apt-get install openjdk-6-jdk`

`echo "deb http://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list`

`sudo apt-get update`

#Say yes to install these packages without verification
`sudo apt-get install sbt`

#Change your fork if needed
`git clone https://github.com/benjaminjackman/looty.git`

`cd looty`

`sbt`

#This will open an interactive sbt console
#it will take some time to download dependencies
#From here on out the commands will be run inside of sbt

#I was informed that several dependencies could not be found
#Therefore I selected retry which worked

#select retry

`fastOptJS`

#This end up successfully building project

**Comment by benjaminjackman** [comment]
#Simpified instructions with jdk-7 support:

#Building Looty on Ubuntu 14.04 Fresh AWS Machine (t2.small w/ 20GB EBS HDD)
#I started a fresh AWS instance then there were the exact commands I managed to run to get it started

`echo "deb http://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list`

`sudo apt-get update`

#Say yes to install these packages without verification
`sudo apt-get install openjdk-7-jdk sbt`

#Change to your fork if needed
`git clone https://github.com/benjaminjackman/looty.git`

`cd looty`

`sbt`

#This will open an interactive sbt console
#it will take some time to download dependencies
#From here on out the commands will be run inside of sbt

#I was informed that several dependencies could not be found
#Therefore I selected retry which worked

#select retry

`fastOptJS`

#This end up successfully building project

**Comment by semasping** [comment]
in Ubuntu works well 
(I had to add my url in manifest.json in permissions)

but "Garena rus" doesn`t work as well as i want 

http://web.poe.garena.ru/character-window/get-stash-items 
return json like :
{
"name": "СтрельщицаЛучная",
"league": "Стандарт",
"classId": 2,
"class": "Ranger",
"level": 52
},
and web.poe.garena.ru/character-window/get-stash-items on post "league=Стандарт&tabIndex=0&tabs=1" return "false",
and always returns "false" when i sending anything to "get-stash-items"

May be web.poe.garena.Com will be better, but i haven`t account there.

**Comment by benjaminjackman** [comment]
The best option is to go on the website you normally use open Dev tools and
watch what the site itself is sending in the network when you click on
different characters inventories and stash tabs. To get the call that gets
all characters for your account you will need to have it open before you
load the page.

From that you can get the base URL atleast. The syntax of the calls might
be different but we can fix that if need be.

**Comment by semasping** [comment]
after using Dev tools:
I understand that problem in russian name of `league`
in Dev tools  - if i use 
`web.poe.garena.ru/character-window/get-stash-items`
with post 
`league=%D0%A1%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82&tabIndex=0&tabs=1`
I get right json.

**Comment by benjaminjackman** [comment]
ah yes uri encoding requires escaping all unicode characters, that makes
sense.

I believe the function to use is encodeURIComponent

if you want I can work on adding in better unicode support for the API
calls, it should be pretty easy.

We will also have to add in a different set of league names, I recently
added a settings page so we can probably put them in there.

**Comment by siumingjjh** [comment]
semasping , do you have a modified RU version
